#cloud-config

apt:
  # Preserves the existing /etc/apt/sources.list
  preserve_sources_list: true

  # Update apt database on first boot (ie run apt-get update)
  update: true

# We know that exactly one data disk will be attached to this VM and it will therefore use lun1 as lun0 is the OS disk
disk_setup:
  /dev/disk/azure/scsi1/lun1:
    table_type: gpt
    layout: True
    overwrite: True

fs_setup:
  - device: /dev/disk/azure/scsi1/lun1
    partition: 1
    filesystem: ext4

mounts:
  - [/dev/disk/azure/scsi1/lun1-part1, /datadrive, ext4, "defaults,nofail"]

# List of packages to install with apt-get
packages:
  - openssh-server
  - rsync
  - apache2

write_files:
  - path: /var/local/cran-mirror-apache.conf
    owner: root:root
    permissions: 0644
    content: |
      <VirtualHost *:80>
        DocumentRoot "/datadrive/mirrordaemon/www/cran"
        <Directory "/datadrive/mirrordaemon/www/cran">
            Options Indexes FollowSymLinks Includes
            AllowOverride All
            Order allow,deny
            Allow from all
            Require all granted
        </Directory>
      </VirtualHost>

# Add the SHM admin (default) and mirrordaemon users
# lock_passwd: Lock the password to disable password login
users:
  - default
  - name: mirrordaemon
    lock_passwd: True
    sudo: False
    ssh_authorized_keys:
      - <external_mirror_public_key>

# Set locale and timezone
locale: en_GB.UTF-8
timezone: <timezone>

# Use Google's NTP servers
# Note that these are incompatible with other servers due to leap-second smearing
ntp:
  pool:
    - time.google.com

runcmd:
  # Suppress apt prompts and warning messages
  - export DEBIAN_FRONTEND=noninteractive

  # Upgrade installation and clean up
  - echo "*** Upgrade and clean up apt-get packages... ***"
  - apt-get -y upgrade
  - apt-get clean

  # Set up disk
  - echo "*** Setting up local disk... ***"
  - mkdir -p /datadrive/mirrordaemon/www/cran
  - ls -alh /datadrive

  # Fix permissions so that mirrordaemon owns its files
  - chown -R mirrordaemon:mirrordaemon /datadrive/mirrordaemon

  # Set up apache: 'restart' runs it now; 'enable' adds it to the list of services run on boot
  - echo "*** Setting up apache server pointing to local disk... ***"
  - mv /var/local/cran-mirror-apache.conf /etc/apache2/sites-enabled/000-default.conf
  - a2enmod rewrite
  - systemctl enable apache2
  - systemctl restart apache2
  - systemctl status apache2


# Shutdown so that we can tell when the job has finished by polling the VM state
power_state:
  mode: poweroff
  message: "Shutting down as a signal that setup is finished"
  timeout: 30
  condition: True
